[Unit]
After=graphical-session.target

[Service]
Environment="DISPLAY=:0"
Environment="WAYLAND_DISPLAY=wayland-0"
Environment="SSH_ASKPASS=/usr/local/bin/reaper-ssh-askpass"
Environment="SSH_ASKPASS_REQUIRE=force"
Environment="DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus"
Environment="XDG_RUNTIME_DIR=/run/user/1000"
ExecStart=
ExecStart=/usr/bin/ssh-agent -D -a %t/openssh_agent
ExecStartPost=/bin/sh -c 'systemctl --user set-environment SSH_AUTH_SOCK=%t/openssh_agent; dbus-update-activation-environment --systemd SSH_AUTH_SOCK=%t/openssh_agent SSH_ASKPASS=/usr/local/bin/reaper-ssh-askpass DISPLAY=:0 WAYLAND_DISPLAY=wayland-0'

[Install]
WantedBy=default.target
